import {
  Box,
  ChakraProvider,
  Grid,
  Heading,
  Image,
  theme,
  VStack,
  Wrap,
  WrapItem,
} from '@chakra-ui/react';
import React from 'react';
import { ColorModeSwitcher } from './ColorModeSwitcher';

function App() {
  return (
    <ChakraProvider theme={theme}>
      <Box textAlign="center" fontSize="l">
        <Grid>
          <ColorModeSwitcher justifySelf="flex-end" />
          <VStack spacing={14}>
            <Image
              width="55%"
              padding={10}
              src="https://readme-typing-svg.herokuapp.com/?center=true&vcenter=true&width=600&height=75&font=rubik&size=30&duration=3000&color=000000&lines=Përshëndetje%2c+My+Name+Is+Jodis!;እው+ሰላም+ነው%2c+My+Name+Is+Jodis!;أهلا%2c+My+Name+Is+Jodis!;Բարեւ+Ձեզ%2c+My+Name+Is+Jodis!;Salam%2c+My+Name+Is+Jodis!;হ্যালো%2c+My+Name+Is+Jodis!;नमस्ते%2c+My+Name+Is+Jodis!;Szia%2c+My+Name+Is+Jodis!;Olá%2c+My+Name+Is+Jodis!;ਸਤ+ਸ੍ਰੀ+ਅਕਾਲ%2c+My+Name+Is+Jodis!;Buna+Ziua%2c+My+Name+Is+Jodis!;Привет%2c+My+Name+Is+Jodis!;Talofa%2c+My+Name+Is+Jodis!;Halò%2c+My+Name+Is+Jodis!;Здраво%2c+My+Name+Is+Jodis!;Mhoro%2c+My+Name+Is+Jodis!;Hola%2c+My+Name+Is+Jodis!;안녕하세요%2c+My+Name+Is+Jodis!;こんにちは%2c+My+Name+Is+Jodis!;Здраво%2c+My+Name+Is+Jodis!;Сайн+Уу%2c+My+Name+Is+Jodis!;नमस्कार%2c+My+Name+Is+Jodis!;Aloha%2c+My+Name+Is+Jodis!;Bonjour%2c+My+Name+Is+Jodis!;שלום%2c+My+Name+Is+Jodis!;Χαίρετε%2c+My+Name+Is+Jodis!;Kamusta%2c+My+Name+Is+Jodis!;Hallo%2c+My+Name+Is+Jodis!;你好%2c+My+Name+Is+Jodis!;Здравейте%2c+My+Name+Is+Jodis!;Добры+Дзень%2c+My+Name+Is+Jodis!;Dia+Dhuit%2c+My+Name+Is+Jodis!;Ciao%2c+My+Name+Is+Jodis!;ສະບາຍດີ%2c+My+Name+Is+Jodis!;Kia+Ora%2c+My+Name+Is+Jodis!"
            />
            <Heading>Software Engineer | Brisbane, Australia!</Heading>
            <Wrap>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="cover"
                  src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg"
                  alt="linkedin.com"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="cover"
                  src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/kaggle.svg"
                  alt="kaggle.com"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="cover"
                  src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/stack-overflow.svg"
                  alt="stackoverflow.com"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="cover"
                  src="https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/codechef.svg"
                  alt="www.codechef.com"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="cover"
                  src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/codesandbox.svg"
                  alt="codesandbox.com"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="cover"
                  src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/dribbble.svg"
                  alt="dribbble.com"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="cover"
                  src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/devto.svg"
                  alt="dev.to"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="cover"
                  src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/behance.svg"
                  alt="www.behance.com"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="cover"
                  src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/hashnode.svg"
                  alt="hashnode.com"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="cover"
                  src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/medium.svg"
                  alt="medium.com"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="cover"
                  src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/codepen.svg"
                  alt="codepen.io"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="cover"
                  src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/hackerrank.svg"
                  alt="hackerrank"
                />
              </WrapItem>
            </Wrap>
            <Heading>Languages and Tools:</Heading>
            <Wrap>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/android/android-original-wordmark.svg"
                  alt="android"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://cdn.worldvectorlogo.com/logos/arduino-1.svg"
                  alt="arduino"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/amazonwebservices/amazonwebservices-original-wordmark.svg"
                  alt="aws"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/microsoft_azure/microsoft_azure-icon.svg"
                  alt="azure"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/gnu_bash/gnu_bash-icon.svg"
                  alt="bash"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/circleci/circleci-icon.svg"
                  alt="circleci"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
                  alt="css3"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/dartlang/dartlang-icon.svg"
                  alt="dart"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://cdn.worldvectorlogo.com/logos/django.svg"
                  alt="django"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg"
                  alt="docker"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/elastic/elastic-icon.svg"
                  alt="elasticsearch"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
                  alt="express"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/figma/figma-icon.svg"
                  alt="figma"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg"
                  alt="firebase"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/pocoo_flask/pocoo_flask-icon.svg"
                  alt="flask"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/flutterio/flutterio-icon.svg"
                  alt="flutter"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/gatsbyjs/gatsbyjs-icon.svg"
                  alt="gatsby"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
                  alt="git"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/go/go-original.svg"
                  alt="go"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/grafana/grafana-icon.svg"
                  alt="grafana"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/heroku/heroku-icon.svg"
                  alt="heroku"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
                  alt="html5"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://api.iconify.design/logos-hugo.svg"
                  alt="hugo"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/ifttt/ifttt-ar21.svg"
                  alt="ifttt"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg"
                  alt="java"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/elasticco_kibana/elasticco_kibana-icon.svg"
                  alt="kibana"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/kotlinlang/kotlinlang-icon.svg"
                  alt="kotlin"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/kubernetes/kubernetes-icon.svg"
                  alt="kubernetes"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg"
                  alt="linux"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/mariadb/mariadb-icon.svg"
                  alt="mariadb"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
                  alt="mysql"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://cdn.worldvectorlogo.com/logos/nextjs-2.svg"
                  alt="nextjs"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nginx/nginx-original.svg"
                  alt="nginx"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/nim-lang/nim-lang-icon.svg"
                  alt="nim"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
                  alt="nodejs"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/2ae2a900d2f041da66e950e4d48052658d850630/icons/pandas/pandas-original.svg"
                  alt="pandas"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original-wordmark.svg"
                  alt="postgresql"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg"
                  alt="postman"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg"
                  alt="python"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://reactnative.dev/img/header_logo.svg"
                  alt="reactnative"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/rust/rust-plain.svg"
                  alt="rust"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
                  alt="sass"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://upload.wikimedia.org/wikipedia/commons/0/05/Scikit_learn_logo_small.svg"
                  alt="scikit_learn"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://raw.githubusercontent.com/detain/svg-logos/780f25886640cef088af994181646db2f6b1a3f8/svg/selenium-logo.svg"
                  alt="selenium"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
                  alt="sqlite"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://upload.wikimedia.org/wikipedia/commons/1/1b/Svelte_Logo.svg"
                  alt="svelte"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/tensorflow/tensorflow-icon.svg"
                  alt="tensorflow"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/vagrantup/vagrantup-icon.svg"
                  alt="vagrant"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://cdn.worldvectorlogo.com/logos/adobe-xd.svg"
                  alt="xd"
                />
              </WrapItem>
              <WrapItem>
                <Image
                  boxSize="30px"
                  objectFit="fit"
                  src="https://www.vectorlogo.zone/logos/zapier/zapier-icon.svg"
                  alt="zapier"
                />
              </WrapItem>
            </Wrap>
          </VStack>
        </Grid>
      </Box>
    </ChakraProvider>
  );
}

export default App;
